# Retail Sales Analysis

In [1]:
# Load Dataset
import pandas as pd
df = pd.read_csv("Sample - Superstore.csv", encoding='latin1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,4574,CA-2016-139395,12/12/2016,12/18/2016,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,TEC-PH-10002103,Technology,Phones,Jabra SPEAK 410,657.9300,7,0.00,184.2204
4574,4575,CA-2016-139395,12/12/2016,12/18/2016,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,FUR-FU-10003724,Furniture,Furnishings,Westinghouse Clip-On Gooseneck Lamps,33.4800,4,0.00,8.7048
4575,4576,CA-2016-139395,12/12/2016,12/18/2016,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,OFF-AR-10003732,Office Supplies,Art,Newell 333,13.9000,5,0.00,3.6140
4576,4577,CA-2016-139395,12/12/2016,12/18/2016,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,OFF-ST-10000885,Office Supplies,Storage,Fellowes Desktop Hanging File Manager,26.8600,2,0.00,6.7150
4577,4578,US-2014-121734,4/11/2014,4/16/2014,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Lewiston,...,83501,West,OFF-BI-10004817,Office Supplies,Binders,GBC Personal VeloBind Strips,9.5840,1,0.20,3.3500

In [3]:
# Basic Info
print("First 5 rows:")
print(df.head())

First 5 rows:
   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [4]:
print("\n Shape of dataset:", df.shape)

 Shape of dataset: (4578, 21)

In [5]:
#  Convert Order Date & Ship Date to datetime
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [6]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,4574,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,TEC-PH-10002103,Technology,Phones,Jabra SPEAK 410,657.9300,7,0.00,184.2204
4574,4575,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,FUR-FU-10003724,Furniture,Furnishings,Westinghouse Clip-On Gooseneck Lamps,33.4800,4,0.00,8.7048
4575,4576,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,OFF-AR-10003732,Office Supplies,Art,Newell 333,13.9000,5,0.00,3.6140
4576,4577,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,49201,Central,OFF-ST-10000885,Office Supplies,Storage,Fellowes Desktop Hanging File Manager,26.8600,2,0.00,6.7150
4577,4578,US-2014-121734,2014-04-11,2014-04-16,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Lewiston,...,83501,West,OFF-BI-10004817,Office Supplies,Binders,GBC Personal VeloBind Strips,9.5840,1,0.20,3.3500

In [7]:
#  Create new columns
df['Year'] = df['Order Date'].dt.year
df['Month'] = df['Order Date'].dt.month
df['MonthName'] = df['Order Date'].dt.strftime('%b')

In [8]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,MonthName
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,Nov
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,Nov
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,Jun
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,Oct
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,Oct
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,4574,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Technology,Phones,Jabra SPEAK 410,657.9300,7,0.00,184.2204,2016,12,Dec
4574,4575,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Furniture,Furnishings,Westinghouse Clip-On Gooseneck Lamps,33.4800,4,0.00,8.7048,2016,12,Dec
4575,4576,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Office Supplies,Art,Newell 333,13.9000,5,0.00,3.6140,2016,12,Dec
4576,4577,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Office Supplies,Storage,Fellowes Desktop Hanging File Manager,26.8600,2,0.00,6.7150,2016,12,Dec
4577,4578,US-2014-121734,2014-04-11,2014-04-16,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Lewiston,...,Office Supplies,Binders,GBC Personal VeloBind Strips,9.5840,1,0.20,3.3500,2014,4,Apr

In [9]:
# Total Sales
df['TotalSales'] = df['Sales']
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Year,Month,MonthName,TotalSales
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,Nov,261.9600
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,Nov,731.9400
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,Jun,14.6200
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,Oct,957.5775
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,Oct,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,4574,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Phones,Jabra SPEAK 410,657.9300,7,0.00,184.2204,2016,12,Dec,657.9300
4574,4575,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Furnishings,Westinghouse Clip-On Gooseneck Lamps,33.4800,4,0.00,8.7048,2016,12,Dec,33.4800
4575,4576,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Art,Newell 333,13.9000,5,0.00,3.6140,2016,12,Dec,13.9000
4576,4577,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Storage,Fellowes Desktop Hanging File Manager,26.8600,2,0.00,6.7150,2016,12,Dec,26.8600
4577,4578,US-2014-121734,2014-04-11,2014-04-16,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Lewiston,...,Binders,GBC Personal VeloBind Strips,9.5840,1,0.20,3.3500,2014,4,Apr,9.5840

In [10]:
# Total Profit
df['TotalProfit'] = df['Profit']
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,MonthName,TotalSales,TotalProfit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,Nov,261.9600,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,Nov,731.9400,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,Jun,14.6200,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,Oct,957.5775,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,Oct,22.3680,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,4574,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Jabra SPEAK 410,657.9300,7,0.00,184.2204,2016,12,Dec,657.9300,184.2204
4574,4575,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Westinghouse Clip-On Gooseneck Lamps,33.4800,4,0.00,8.7048,2016,12,Dec,33.4800,8.7048
4575,4576,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Newell 333,13.9000,5,0.00,3.6140,2016,12,Dec,13.9000,3.6140
4576,4577,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Fellowes Desktop Hanging File Manager,26.8600,2,0.00,6.7150,2016,12,Dec,26.8600,6.7150
4577,4578,US-2014-121734,2014-04-11,2014-04-16,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Lewiston,...,GBC Personal VeloBind Strips,9.5840,1,0.20,3.3500,2014,4,Apr,9.5840,3.3500

In [11]:
# Clean missing values
df = df.dropna()
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Year,Month,MonthName,TotalSales,TotalProfit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,Nov,261.9600,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,Nov,731.9400,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,Jun,14.6200,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,Oct,957.5775,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,Oct,22.3680,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,4574,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Jabra SPEAK 410,657.9300,7,0.00,184.2204,2016,12,Dec,657.9300,184.2204
4574,4575,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Westinghouse Clip-On Gooseneck Lamps,33.4800,4,0.00,8.7048,2016,12,Dec,33.4800,8.7048
4575,4576,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Newell 333,13.9000,5,0.00,3.6140,2016,12,Dec,13.9000,3.6140
4576,4577,CA-2016-139395,2016-12-12,2016-12-18,Standard Class,MG-17650,Matthew Grinstein,Home Office,United States,Jackson,...,Fellowes Desktop Hanging File Manager,26.8600,2,0.00,6.7150,2016,12,Dec,26.8600,6.7150
4577,4578,US-2014-121734,2014-04-11,2014-04-16,Standard Class,SE-20110,Sanjit Engle,Consumer,United States,Lewiston,...,GBC Personal VeloBind Strips,9.5840,1,0.20,3.3500,2014,4,Apr,9.5840,3.3500

In [12]:
# Monthly Sales Summary
monthly_sales = df.groupby(['Year', 'Month'])['TotalSales'].sum().reset_index()
monthly_sales

    Year  Month  TotalSales
0   2014      1   6221.2980
1   2014      2   1362.5060
2   2014      3  33887.9310
3   2014      4  13391.8550
4   2014      5  11089.2350
5   2014      6  24693.5356
6   2014      7  21470.4440
7   2014      8  15682.8285
8   2014      9  46543.1318
9   2014     10  15259.9610
10  2014     11  41441.7980
11  2014     12  35121.7485
12  2015      1   6350.7880
13  2015      2   4390.1950
14  2015      3  21112.0690
15  2015      4  15141.1470
16  2015      5   6592.7280
17  2015      6   8496.5730
18  2015      7  22436.9230
19  2015      8  22149.9320
20  2015      9  30294.9180
21  2015     10  15318.3665
22  2015     11  26074.4503
23  2015     12  35779.2892
24  2016      1   5824.5750
25  2016      2   5880.8100
26  2016      3  22852.1520
27  2016      4  23422.7920
28  2016      5  25993.0300
29  2016      6  15271.6600
30  2016      7  21959.7630
31  2016      8  14315.7518
32  2016      9  32821.5979
33  2016     10  12453.1440
34  2016     11  28481.3858
35  2016     12  34062.3790
36  2017      1  16196.8670
37  2017      2   7832.3420
38  2017      3  17403.4808
39  2017      4  24015.7821
40  2017      5  20924.1970
41  2017      6  19481.5225
42  2017      7  17736.4750
43  2017      8  25180.1260
44  2017      9  39853.8240
45  2017     10  44861.6020
46  2017     11  68485.1318
47  2017     12  38431.9998

In [13]:
#  Create Year-Month column for plotting & Power BI
monthly_sales['YearMonth'] = monthly_sales['Year'].astype(str) + "-" + monthly_sales['Month'].astype(str).str.zfill(2)

In [14]:
# Save cleaned data
df.to_csv("superstore_clean.csv", index=False)
monthly_sales.to_csv("monthly_sales.csv", index=False)

In [16]:
print("\n Cleaned files saved:")
print("- superstore_clean.csv")
print("- monthly_sales.csv")

 Cleaned files saved:
- superstore_clean.csv
- monthly_sales.csv